"use strict";

// this file is generated by a function in server-utils.js

/*
 * This is part of base server, the table contains all socket
 * handler names.  This is to give ability to give access rights
 * to users, and not to accidentally expose functionality to non
 * priveleged users
 */
module.exports = function(sequelize, DataTypes) {
	var AppAction = sequelize.define("AppAction", {
		//appActionId: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
		name: { type: DataTypes.STRING, allowNull: false, unique: 'user_action_name_idx'},
    // contains table names this app action touches, if specified of course
		crud: { type: DataTypes.JSON, allowNull: true },
	}, {
		// adds deletedAt column
		//paranoid: true
	});

	/**
	 * Lists all possible handlers, isn't meant to be used directly by user.  
	 * The AppUser must be assigned a user group
	 */
	AppAction.associate= function(models) {
		AppAction.belongsToMany(models.AppUserGroup, {through: 'AppActionACL'});
	};

	return AppAction;

};
